[package]
name = "mainline"
version = "0.1.0"
authors = ["nuh.dev"]
edition = "2018"
description = "Simple, robust, BitTorrent's Mainline DHT implementation"
homepage = "https://github.com/nuhvi/mainline"
license = "MIT"
keywords = ["bittorrent", "torrent", "dht", "kademlia", "mainline"]
categories = ["network-programming"]
repository = "https://github.com/nuhvi/mainline"

[dependencies]
rand = "0.8.5"
thiserror = "1.0.49"
serde_bencode = "^0.2.4"
serde = { version = "1.0.133", features = ["derive"] }
serde_bytes = "0.11.5"
serde_derive = "^1.0.0"
