[package]
name = "dht_size_estimate_simulation"
version = "0.1.0"
authors = ["nuh.dev"]
edition = "2018"

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
ctrlc = "3.4.5"
mainline = { version = "3.0.1", path = "../.." }
num_cpus = "1.16.0"
plotters = "0.3.7"
statrs = "0.17.1"
